# Generated by Django 3.2 on 2021-06-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myself', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logID', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
